In [1]:
'''
../data/past_average_congestion.csv
파일을 읽어와 dataframe으로 로드
'''
import pandas as pd

df = pd.read_csv('../../data/past_average_congestion.csv')
df

,subwayLine,stationName,stationCode,updnLine,dow,hh,mm,prevStationName,prevStationCode,congestionCar,getOffCarRate,next_station_congestion,totalCongestion,platformPeople,platformCongestion
0,2호선,강남역,222,1,FRI,17,0,역삼역,221,"[67.8, 77.8, 75.8, 75.8, 71.8, 82.8, 80.8, 86....","[5.0, 9.0, 11.0, 16.0, 12.0, 15.0, 12.0, 8.0, ...",NaN,[],[],[]
1,2호선,강남역,222,1,FRI,17,10,역삼역,221,"[108.0, 87.0, 105.0, 109.0, 115.0, 107.0, 111....","[6.0, 10.0, 11.0, 16.0, 12.0, 15.0, 12.0, 7.0,...",NaN,[],[],[]
2,2호선,강남역,222,1,FRI,17,20,역삼역,221,"[103.2, 89.2, 107.4, 120.8, 103.4, 99.2, 135.0...","[5.2, 11.0, 10.0, 15.0, 12.0, 15.0, 13.0, 8.0,...",NaN,[],[],[]
3,2호선,강남역,222,1,FRI,17,30,역삼역,221,"[100.4, 83.2, 99.4, 119.6, 108.6, 113.6, 113.6...","[6.0, 10.0, 10.0, 15.0, 11.0, 16.0, 13.0, 8.0,...",NaN,[],[],[]
4,2호선,강남역,222,1,FRI,17,40,역삼역,221,"[78.4, 93.4, 94.4, 98.8, 102.2, 91.6, 105.8, 9...","[6.0, 10.0, 10.0, 14.0, 11.0, 15.0, 14.0, 7.0,...",NaN,[],[],[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1003,7호선,신풍역,743,1,WED,19,10,보라매역,742,"[62.125, 60.75, 64.875, 77.75, 59.375, 64.125,...","[8.875, 8.0, 8.875, 18.25, 14.125, 13.25, 13.8...","[55.125, 58.75, 60.75, 62.875, 55.125, 58.75, ...","[55.125, 58.75, 60.75, 62.875, 55.125, 58.75, ...","[0.0, 4.58, 2.61, 0.0, 6.62, 4.99, 0.0, 1.34]","[0.0, 17.74, 10.12, 0.0, 25.65, 19.36, 0.0, 5.19]"
1004,7호선,신풍역,743,1,WED,19,20,보라매역,742,"[55.375, 56.375, 55.375, 53.375, 54.375, 69.87...","[9.0, 7.875, 10.125, 17.125, 13.875, 13.5, 14....","[57.75, 60.125, 58.5, 56.75, 54.625, 68.125, 5...","[57.75, 60.125, 58.5, 56.75, 54.625, 68.125, 5...","[11.77, 13.1, 13.97, 20.02, 12.47, 12.29, 11.7...","[45.64, 50.79, 54.15, 77.62, 48.34, 47.65, 45...."
1005,7호선,신풍역,743,1,WED,19,30,보라매역,742,"[42.375, 46.875, 45.125, 56.875, 41.5, 54.25, ...","[9.25, 8.25, 10.375, 18.125, 14.0, 13.0, 13.87...","[48.125, 51.0, 52.25, 60.375, 46.875, 60.25, 5...","[48.125, 51.0, 52.25, 60.375, 46.875, 60.25, 5...","[15.47, 12.79, 18.89, 22.09, 17.9, 20.88, 19.6...","[59.97, 49.56, 73.22, 85.63, 69.36, 80.95, 76...."
1006,7호선,신풍역,743,1,WED,19,40,보라매역,742,"[35.875, 48.875, 40.875, 38.875, 40.625, 41.12...","[8.875, 9.75, 9.625, 18.875, 13.875, 13.875, 1...","[36.75, 51.5, 40.75, 38.0, 39.75, 41.625, 34.0...","[36.75, 51.5, 40.75, 38.0, 39.75, 41.625, 34.0...","[6.49, 11.82, 6.09, 10.34, 7.62, 9.93, 4.96, 5...","[25.17, 45.83, 23.62, 40.08, 29.53, 38.49, 19...."
1007,7호선,신풍역,743,1,WED,19,50,보라매역,742,"[36.5, 42.0, 39.75, 42.0, 43.75, 43.0, 36.5, 3...","[7.875, 9.75, 10.125, 19.75, 15.0, 12.375, 13....","[35.0, 39.5, 37.25, 39.375, 40.125, 40.75, 34....","[35.0, 39.5, 37.25, 39.375, 40.125, 40.75, 34....","[2.2, 2.55, 2.44, 9.07, 4.7, 4.91, 4.19, 1.47]","[8.52, 9.89, 9.46, 35.16, 18.22, 19.05, 16.25,..."

In [2]:
'''
stationName, dow, hh, mm 순으로 정렬
'''
df = df.sort_values(by=['stationName', 'dow', 'hh', 'mm'])
df

,subwayLine,stationName,stationCode,updnLine,dow,hh,mm,prevStationName,prevStationCode,congestionCar,getOffCarRate,next_station_congestion,totalCongestion,platformPeople,platformCongestion
0,2호선,강남역,222,1,FRI,17,0,역삼역,221,"[67.8, 77.8, 75.8, 75.8, 71.8, 82.8, 80.8, 86....","[5.0, 9.0, 11.0, 16.0, 12.0, 15.0, 12.0, 8.0, ...",NaN,[],[],[]
1,2호선,강남역,222,1,FRI,17,10,역삼역,221,"[108.0, 87.0, 105.0, 109.0, 115.0, 107.0, 111....","[6.0, 10.0, 11.0, 16.0, 12.0, 15.0, 12.0, 7.0,...",NaN,[],[],[]
2,2호선,강남역,222,1,FRI,17,20,역삼역,221,"[103.2, 89.2, 107.4, 120.8, 103.4, 99.2, 135.0...","[5.2, 11.0, 10.0, 15.0, 12.0, 15.0, 13.0, 8.0,...",NaN,[],[],[]
3,2호선,강남역,222,1,FRI,17,30,역삼역,221,"[100.4, 83.2, 99.4, 119.6, 108.6, 113.6, 113.6...","[6.0, 10.0, 10.0, 15.0, 11.0, 16.0, 13.0, 8.0,...",NaN,[],[],[]
4,2호선,강남역,222,1,FRI,17,40,역삼역,221,"[78.4, 93.4, 94.4, 98.8, 102.2, 91.6, 105.8, 9...","[6.0, 10.0, 10.0, 14.0, 11.0, 15.0, 14.0, 7.0,...",NaN,[],[],[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499,2호선,역삼역,221,1,WED,19,10,선릉역,220,"[41.0, 41.6, 49.0, 48.8, 44.4, 51.6, 54.0, 44....","[5.0, 8.0, 11.0, 10.0, 11.0, 10.0, 11.0, 10.0,...","[42.2, 46.0, 56.2, 55.2, 49.0, 52.0, 58.0, 54....","[42.2, 46.0, 56.2, 55.2, 49.0, 52.0, 58.0, 54....","[5.2, 12.36, 20.14, 18.05, 15.17, 8.9, 15.9, 2...","[20.16, 47.93, 78.08, 69.95, 58.82, 34.48, 61...."
500,2호선,역삼역,221,1,WED,19,20,선릉역,220,"[35.6, 48.6, 47.8, 55.6, 49.8, 52.4, 53.4, 46....","[5.0, 8.0, 11.0, 10.0, 11.0, 10.0, 11.0, 10.0,...","[46.8, 54.8, 60.0, 64.6, 59.0, 62.0, 67.4, 56....","[46.8, 54.8, 60.0, 64.6, 59.0, 62.0, 67.4, 56....","[20.77, 16.14, 27.93, 23.3, 23.48, 23.74, 31.8...","[80.5, 62.56, 108.27, 90.29, 91.03, 92.03, 123..."
501,2호선,역삼역,221,1,WED,19,30,선릉역,220,"[29.2, 38.4, 41.8, 39.4, 43.4, 40.8, 45.4, 37....","[5.0, 8.0, 11.0, 10.0, 11.0, 10.0, 11.0, 10.0,...","[36.2, 42.6, 46.4, 49.6, 44.8, 48.6, 52.8, 44....","[36.2, 42.6, 46.4, 49.6, 44.8, 48.6, 52.8, 44....","[13.54, 11.64, 14.72, 22.62, 9.88, 19.01, 19.8...","[52.47, 45.1, 57.04, 87.69, 38.29, 73.67, 76.8..."
502,2호선,역삼역,221,1,WED,19,40,선릉역,220,"[32.6, 37.6, 46.0, 46.0, 33.6, 38.8, 39.0, 37....","[5.0, 8.0, 11.0, 10.0, 11.0, 10.0, 11.0, 10.0,...","[32.8, 42.8, 53.6, 49.8, 42.6, 47.6, 47.2, 46....","[32.8, 42.8, 53.6, 49.8, 42.6, 47.6, 47.2, 46....","[2.93, 13.13, 20.26, 13.44, 20.31, 20.29, 19.9...","[11.35, 50.9, 78.51, 52.09, 78.73, 78.64, 77.4..."
503,2호선,역삼역,221,1,WED,19,50,선릉역,220,"[38.8, 38.8, 41.2, 42.0, 33.0, 41.2, 48.8, 27....","[5.0, 8.0, 11.0, 10.0, 11.0, 10.0, 11.0, 10.0,...","[43.0, 46.2, 49.4, 49.8, 37.6, 48.6, 55.0, 34....","[43.0, 46.2, 49.4, 49.8, 37.6, 48.6, 55.0, 34....","[9.82, 16.81, 20.37, 19.2, 13.17, 18.43, 18.51...","[38.08, 65.14, 78.96, 74.42, 51.04, 71.44, 71...."

In [3]:
'''
stationName=역삼역, dow=FRI, hh=18, mm=10 인 데이터 추출
'''
df_yeoksam = df[(df['stationName'] == '역삼역') & (df['dow'] == 'FRI') & (df['hh'] == 18) & (df['mm'] == 10)]
df_yeoksam

,subwayLine,stationName,stationCode,updnLine,dow,hh,mm,prevStationName,prevStationCode,congestionCar,getOffCarRate,next_station_congestion,totalCongestion,platformPeople,platformCongestion
385,2호선,역삼역,221,1,FRI,18,10,선릉역,220,"[115.2, 106.6, 106.6, 104.4, 112.0, 107.6, 94....","[8.2, 8.0, 13.2, 9.0, 9.8, 7.0, 12.0, 10.0, 13...","[98.0, 86.8, 101.2, 92.6, 104.6, 86.0, 85.0, 1...","[98.0, 86.8, 101.2, 92.6, 104.6, 86.0, 85.0, 1...","[0.0, 0.0, 13.87, 0.0, 5.72, 0.0, 2.8, 9.89, 9...","[0.0, 0.0, 53.77, 0.0, 22.18, 0.0, 10.87, 38.3..."

In [5]:
df_gangnam = df[(df['stationName'] == '강남역') & (df['dow'] == 'FRI') & (df['hh'] == 18) & (df['mm'] == 10)]
df_gangnam

,subwayLine,stationName,stationCode,updnLine,dow,hh,mm,prevStationName,prevStationCode,congestionCar,getOffCarRate,next_station_congestion,totalCongestion,platformPeople,platformCongestion
7,2호선,강남역,222,1,FRI,18,10,역삼역,221,"[98.0, 86.8, 101.2, 92.6, 104.6, 86.0, 85.0, 1...","[7.0, 9.2, 11.0, 14.0, 10.0, 15.0, 14.0, 7.0, ...",NaN,[],[],[]